config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'

  resources :events

  namespace :admin do
    resources :events do
      member do
        post :publish
        post :hide
      end
    end
  end

  namespace :account do
    resources :events do
      member do
        post :publish
        post :hide 
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    is_admin
  end

  has_many :events
end

app/controllers/account/events_controller.rb
class Account::EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_event_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @events = current_user.events.order("created_at DESC")
  end

  def publish
    @event = Event.find(params[:id])
    @event.publish!
    redirect_to :back
  end

  def hide
    @event = Event.find(params[:id])
    @event.hide!
    redirect_to :back
  end

  def edit
    find_event_and_check_permission
  end

  def update
    find_event_and_check_permission

    if @event.update(event_params)
      redirect_to account_events_path, notice: "编辑成功"
    else
      render :edit
    end
  end

  def destroy
    find_event_and_check_permission

    @event.destroy

    redirect_to account_events_path, alert: "删除成功"
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def find_event_and_check_permission
    @event = Event.find(params[:id])

    if current_user != @event.user
      redirect_to root_path, alert: "You have no permission"
    end
  end

  def event_params
    params.require(:event).permit(:title, :description, :endtime, :important_class, :executive_method,:is_hidden)
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin
  layout "admin"

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.order("created_at DESC")
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    if @event.save
      redirect_to admin_events_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to admin_events_path
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])

    @event.destroy

    redirect_to admin_events_path
  end

  def publish
    @event = Event.find(params[:id])
    @event.publish!
    redirect_to :back
  end

  def hide
    @event = Event.find(params[:id])
    @event.hide!
    redirect_to :back
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :endtime, :important_class, :executive_method, :is_hidden)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :find_event_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @events = Event.where(:is_hidden => false).order("created_at DESC")
  end

  def show
    @event = Event.find(params[:id])

    if @event.is_hidden
      flash[:warning] = "This events already archived"
      redirect_to root_path
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
    find_event_and_check_permission
  end

  def update
    find_event_and_check_permission
    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    find_event_and_check_permission

    @event.destroy

    redirect_to events_path, alert: "删除成功"
  end

  private

  def find_event_and_check_permission
  @event = Event.find(params[:id])

    if current_user != @event.user
      redirect_to root_path, alert: "You have no permission"
    end
  end


  def event_params
    params.require(:event).permit(:title, :description, :endtime, :important_class, :executive_method, :is_hidden)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "Long the bitcoin, short the world!"
  end
end

app/helpers/account/events_helper.rb
module Account::EventsHelper
  def render_account_event_status(event)
    if event.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-unlock")
    end
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  def render_admin_event_status(event)
    if event.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-unlock")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/events/edit.html.erb
<h1> 编辑事件 </h1>

<%= simple_form_for [:admin, @event ] do |f| %>

<%= f.input :title , label: "名称" %>
<%= f.input :description, label: "内容" %>
<%= f.input :endtime, label: "截止时间" %>
<%= f.input :important_class, label: "重要紧急程度" %>
<%= f.input :executive_method, label: "执行方法" %>
<%= f.input :is_hidden, label: "隐藏"  %>

  <%= f.submit "提交", class: "btn btn-danger" %>
<% end %>

app/views/admin/events/index.html.erb
<h2>事件管理--管理员</h2>

<div class="pull-right">
  <%= link_to("增加一个事件", new_admin_event_path, :class => "btn btn-default" ) %>
</div>

<br><br>

<table class="table table-bordered">
  <% @events.each do |event| %>
  <tr>
    <td>
      <%= render_admin_event_status(event) %>
      <%= link_to(event.title, admin_event_path(event)) %>
    </td>
    <td>
      <%= event.user.email %>
    </td>
    <td>
      <%= link_to("编辑", edit_admin_event_path(event)) %>
      <%= link_to("删除", admin_event_path(event), :method => :delete, :data => { :confirm => "Are you sure?" }) %>

      <% if event.is_hidden %>
        <%= link_to("显示", publish_admin_event_path(event), :method => :post, :class => "btn btn-xs btn-success") %>
      <% else %>
        <%= link_to("隐藏", hide_admin_event_path(event), :method => :post, :class => "btn btn-xs btn-danger") %>
      <% end %>
    </td>
    <td>
      <%= event.created_at %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/events/new.html.erb
<h1> 新增事件 </h1>

<%= simple_form_for [:admin,@event] do |f| %>

<%= f.input :title , label: "名称" %>
<%= f.input :description, label: "内容" %>
<%= f.input :endtime, label: "截止时间" %>
<%= f.input :important_class, label: "重要紧急程度" %>
<%= f.input :executive_method, label: "执行方法" %>
<%= f.input :is_hidden, label: "隐藏"  %>

  <%= f.submit "提交", class: "btn btn-danger" %>
<% end %>

app/views/admin/events/show.html.erb
<h1> <%= @event.title %> </h1>

<p>
  <%= simple_format(@event.description) %>
  <h6> 重要紧急程度 ：<%= @event.important_class %> </h6>
  <h6> 执行方法 ：<%= @event.executive_method %> </h6>
  <h6> 事件截止日期 ：<%= @event.endtime %> </h6>
</p>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 I-Home
        <br>Design by Fengkai
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">I-Home | 家庭管理系统 V1.0版</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
              <li><%= link_to("注册", new_user_registration_path) %> </li>
              <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
            <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Hi!, <%= current_user.email %>
                  <b class="caret"></b>
                </a>

                <ul class="dropdown-menu">
                  <li><%= link_to("我的事件", account_events_path) %></li>
                  <li class="divider"> </li>

                  <% if current_user.admin? %>
                    <li> <%= link_to("管理员面板", admin_events_path) %> </li>
                  <% end %>

                  <li> <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>

<%= f.input :title , label: "名称" %>
<%= f.input :description, label: "内容" %>
<%= f.input :endtime, label: "截止时间" %>
<%= f.input :important_class, label: "重要紧急程度" %>
<%= f.input :executive_method, label: "执行方法" %>
<%= f.input :is_hidden, label: "隐藏"  %>

  <%= f.submit "提交", class: "btn btn-danger" %>
<% end %>

app/views/events/edit.html.erb
<!-- 浏览暂时不需要编辑功能 -->

app/views/events/index.html.erb
<div class="pull-right">
  <%= link_to("增加一个事件", new_event_path, :class => "btn btn-primary" ) %>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">

    <table class="table table-bordered table-hover">
      <thead>
        <th class="active">#</th>
        <th class="active">事件名称</th>
        <th class="active">创建者</th>
        <th class="active">创建时间</th>
      </thead>

      <tbody>
        <% @events.each do |event| %>
        <tr>
          <th>#</th>
          <td>
            <%= link_to(event.title, event_path(event)) %>
          </td>
          <td>
            <%= event.user.email %>
          </td>
          <td>
            <%= event.created_at %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/events/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1> 增加事件 </h1>

  <hr>

  <%= render "form" %>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">

    <div class="panel panel-default">

      <div class="panel-heading">
        <h4> <%= @event.title %> </h4>
      </div>

      <div class="panel-body">
        <h5> <%= simple_format(@event.description) %> </h5>
      </div>

      <ul class="list-group">
        <li class="list-group-item">重要紧急程度 ：<%= @event.important_class %></li>
        <li class="list-group-item">执行方法 ：<%= @event.executive_method %></li>
        <li class="list-group-item">事件截止日期 ：<%= @event.endtime %></li>
      </ul>

      <div class="panel-footer">Attachment here</div>

    </div>

  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I-Home</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">

      <%= render "common/navbar" %>
      <%= render "common/flashes" %>

      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
            <li class="active"><%= link_to("事件清单", admin_events_path ) %> </li>
          </ul>
        </div>

        <div class="col-md-10">
            <%= yield %>
        </div>
      </div>

    </div>

    <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I-Home</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>
<h2>I-Home 用于家庭和工作管理</h2>